# --------------------------------------
# Hexo Butterfly Theme Configuration
# If you have any questions, please refer to the documentation
# Chinese: https://butterfly.js.org/
# English: https://butterfly.js.org/en/
# --------------------------------------

# --------------------------------------
# Navigation Settings
# --------------------------------------

nav:
  # Navigation bar logo image
  logo:
  display_title: true
  display_post_title: true
  # Whether to fix navigation bar
  fixed: false

menu:
  首页: / || fas fa-home
  归档: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  #说说: /artitalk/ || fas fa-comment-dots
  友链: /link/ || fas fa-link
  关于: /about/ || fas fa-heart

# --------------------------------------
# Code Blocks Settings
# --------------------------------------

code_blocks:
  # Code block theme: darker / pale night / light / ocean / false
  theme: light
  macStyle: false
  # Code block height limit (unit: px)
  height_limit: false
  word_wrap: false

  # Toolbar
  copy: true
  language: true
  # true: shrink the code blocks | false: expand the code blocks | none: expand code blocks and hide the button
  shrink: false
  fullpage: false

# copy settings
copy:
  enable: true
  copyright:
    enable: false
    limit_count: 50

# Social media links
social:
  fab fa-github: https://github.com/csfwff || Github
  fas fa-envelope: mailto:csfwff@163.com || Email
  iconfont icon-netease-cloud-music-fill: https://music.163.com/#/user/home?id=40898262 || 网易云
  fab fa-qq: tencent://message/?uin=873997011 || QQ
  fab fa-weixin: https://tmx.fishpi.cn/image/add_weixin.jpg || 微信

# --------------------------------------
# Image Settings
# --------------------------------------

favicon: https://tmx.fishpi.cn/image/favicon.png

avatar:
  img: https://tmx.fishpi.cn/image/head.jpg
  effect: false

disable_top_img: false

default_top_img: https://tmx.fishpi.cn/img/pic_1707295359109.png

index_img: https://tmx.fishpi.cn/img/pic_1707295359109.png

archive_img: https://tmx.fishpi.cn/img/pic_1707295359109.png

tag_img: https://tmx.fishpi.cn/img/pic_1707298830589.png

tag_per_img:

category_img: https://tmx.fishpi.cn/img/pic_1707299090893.png

category_per_img:

footer_img: false

background:

cover:
  index_enable: true
  aside_enable: true
  archives_enable: true
  default_cover:
    - https://tmx.fishpi.cn/img/pic_1707295359109.png
    - https://tmx.fishpi.cn/img/pic_1707299090893.png
    - https://tmx.fishpi.cn/img/pic_1707298830589.png

error_img:
  flink: /img/friend_404.gif
  post_page: /img/404.jpg

error_404:
  enable: false
  subtitle: 'Page Not Found'
  background: https://i.loli.net/2020/05/19/aKOcLiyPl2JQdFD.png

post_meta:
  page:
    date_type: created
    date_format: date
    categories: true
    tags: true
    label: true
  post:
    position: left
    date_type: both
    date_format: date
    categories: true
    tags: true
    label: true

# --------------------------------------
# Index page settings
# --------------------------------------

index_site_info_top:
index_top_img_height:

subtitle:
  enable: true
  effect: true
  loop: true
  typed_option:
  source: 4
  sub:
    - Forever alone forever sad

index_layout: 3

index_post_content:
  method: 2
  length: 500

# --------------------------------------
# Post Settings
# --------------------------------------

toc:
  post: true
  page: false
  number: true
  expand: false
  style_simple: false
  scroll_percent: true

post_copyright:
  enable: true
  decode: false
  author_href:
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

reward:
  enable: true
  text:
  QR_code:
    - img: https://tmx.fishpi.cn/image/wechatpay.png
      link:
      text: wechat
    - img: https://tmx.fishpi.cn/image/alipay.jpg
      link:
      text: alipay

post_edit:
  enable: false
  url:

related_post:
  enable: true
  limit: 6
  date_type: created

post_pagination: 1

noticeOutdate:
  enable: false
  style: flat
  limit_day: 500
  position: top
  message_prev: It has been
  message_next: days since the last update, the content of the article may be outdated.

photofigcaption: false

# --------------------------------------
# Footer Settings
# --------------------------------------

footer:
  nav:
  owner:
    enable: true
    since: 2017
  copyright:
    enable: true
    version: true
  custom_text: 我是不慎落入世界的一滴水墨<br/><a href="https://icp.gov.moe/?keyword=20211205" target="_blank">萌ICP备20211205号</a><br/>所有图片来自自己拍摄，绘画，截图，或<a href="https://pixabay.com/">免费免版税图片库pixabay</a><br/><a href="https://www.upyun.com/?utm_source=lianmeng&utm_medium=referral" target="_blank" style="display:flex;flex-direction:row;align-items:center;justify-content:center">本网站由<img src="https://tmx.fishpi.cn/image/又拍云_logo6.png" width="60">提供CDN加速/云存储服务</a>

# --------------------------------------
# Aside Settings
# --------------------------------------

aside:
  enable: true
  hide: false
  button: true
  mobile: true
  position: right
  display:
    archive: true
    tag: true
    category: true
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
      text: Follow Me
      link: https://github.com/csfwff
  card_announcement:
    enable: true
    content: <small><center><br/></center></small><small><center>世界并没有变，变的只有我自己。</center></small><link rel="stylesheet" href="https://tmx.fishpi.cn/cdn/APlayer.min.css"><script src="https://tmx.fishpi.cn/cdn/APlayer.min.js"></script><script src="https://tmx.fishpi.cn/cdn/Meting.min.js"></script><meting-js server="netease" type="song" id="1381202055"></meting-js><small><center>如果你觉得我们聊得来</center></small><small><center>可以请我吃个果冻~</center></small><small><center>如果有机会</center></small><small><center>我会请你喝可乐~</center></small><center><img src="https://tmx.fishpi.cn/image/reward1.png" width="240"/></center><center><a href="https://www.foreverblog.cn/" target="_blank" > <img src="https://foreverblog.cn/assets/logo/logo_en_default.png" alt="" style="width:auto;height:16px;"> </a></center><center><a href="https://www.foreverblog.cn/go.html" target="_blank" > <img src="https://foreverblog.cn/assets/logo/wormhole_3.gif" alt="" style="width:auto;height:32px;" title="穿梭虫洞-随机访问十年之约友链博客"> </a></center><center><a href="https://www.travellings.cn/go.html" target="_blank" rel="noopener" title="开往-友链接力"><img src="https://www.travellings.cn/assets/logo.gif" alt="开往-友链接力" width="120"></a></center>
  card_recent_post:
    enable: true
    limit: 5
    sort: date
    sort_order:
  card_newest_comments:
    enable: false
    sort_order:
    limit: 6
    storage: 10
    avatar: true
  card_categories:
    enable: true
    limit: 8
    expand: none
    sort_order:
  card_tags:
    enable: true
    limit: 40
    color: false
    custom_colors:
    orderby: random
    order: 1
    sort_order:
  card_archives:
    enable: true
    type: monthly
    format: MMMM YYYY
    order: -1
    limit: 8
    sort_order:
  card_post_series:
    enable: true
    series_title: false
    orderBy: 'date'
    order: -1
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true
    sort_order:
    runtime_date:

busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

# --------------------------------------
# Bottom right button
# --------------------------------------

rightside_bottom:

translate:
  enable: false
  default: 繁
  defaultEncoding: 2
  translateDelay: 0
  msgToTraditionalChinese: '繁'
  msgToSimplifiedChinese: '簡'

readmode: true

darkmode:
  enable: true
  button: true
  autoChangeMode: false
  start:
  end:

rightside_scroll_percent: false

rightside_item_order:
  enable: false
  hide:
  show:

rightside_config_animation: true

# --------------------------------------
# Global Settings
# --------------------------------------

anchor:
  auto_update: false
  click_to_scroll: false

wordcount:
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true

# --------------------------------------
# Math
# --------------------------------------

math:
  use:
  per_page: false
  hide_scrollbar: true

  mathjax:
    enableMenu: true
    tags: none

  katex:
    copy_tex: false

# --------------------------------------
# Search
# --------------------------------------

search:
  use:
  placeholder:

  algolia_search:
    hitsPerPage: 6

  local_search:
    preload: false
    top_n_per_article: 1
    unescape: false
    pagination:
      enable: false
      hitsPerPage: 8
    CDN:

  docsearch:
    appId:
    apiKey:
    indexName:
    option:

# --------------------------------------
# Share System
# --------------------------------------

share:
  use: sharejs

  sharejs:
    sites: facebook,twitter,wechat,weibo,qq

  addtoany:
    item: facebook,twitter,wechat,sina_weibo,facebook_messenger,email,copy_link

# --------------------------------------
# Comments System
# --------------------------------------

comments:
  use:
    - Waline
  text: true
  lazyload: false
  count: false
  card_post_count: false

disqus:
  shortname:
  apikey:

disqusjs:
  shortname:
  apikey:
  option:

livere:
  uid:

gitalk:
  client_id:
  client_secret:
  repo: csfwff.github.io
  owner: csfwff
  admin: csfwff
  option:

valine:
  appId:
  appKey:
  avatar: monsterid
  serverURLs:
  bg:
  visitor: false
  option:

waline:
  serverURL: https://waline.sszsj.com
  pageview: false
  option:
    avatar: monsterid
    requiredFields: nick,mail
    visitor: false
    locale:
      placeholder: 记得留下你的昵称和邮箱....可以快速收到回复（评论需要审核哟，不要着急）

utterances:
  repo:
  issue_term: pathname
  light_theme: github-light
  dark_theme: photon-dark
  js:
  option:

facebook_comments:
  app_id:
  user_id:
  pageSize: 10
  order_by: social
  lang: en_US

twikoo:
  envId:
  region:
  visitor: false
  option:

giscus:
  repo:
  repo_id:
  category_id:
  light_theme: light
  dark_theme: dark
  js:
  option:

remark42:
  host:
  siteId:
  option:

artalk:
  server:
  site:
  visitor: false
  option:

artitalk:
  enable: true
  appId: sxM27aiIaPbf7Lr70hQm6xaq-MdYXbMMI
  appKey: lBxwLUbQjn1o42hQoWl6tTDM

# --------------------------------------
# Chat Services
# --------------------------------------

chat:
  use:
  rightside_button: false
  button_hide_show: false

chatra:
  id:

tidio:
  public_key:

crisp:
  website_id:

# --------------------------------------
# Analysis
# --------------------------------------

baidu_analytics:

google_analytics: G-L2FFP00RKZ

cloudflare_analytics:

microsoft_clarity:

umami_analytics:
  enable: false
  serverURL:
  script_name: script.js
  website_id:
  option:
  UV_PV:
    site_uv: false
    site_pv: false
    page_pv: false
    token:

google_tag_manager:
  tag_id:
  domain:

cnzz_analytics: 1280246701

# --------------------------------------
# Advertisement
# --------------------------------------

google_adsense:
  enable: false
  auto_ads: true
  js: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
  client:
  enable_page_level_ads: true

ad:
  index:
  aside:
  post:

# --------------------------------------
# Verification
# --------------------------------------

site_verification:

# --------------------------------------
# Beautify / Effect
# --------------------------------------

# theme_color:
#   enable: true
#   main: "#49B1F5"

category_ui:
tag_ui:

rounded_corners_ui: true

text_align_justify: false

mask:
  header: true
  footer: true

preloader:
  enable: true
  source: 1
  pace_css_url:

enter_transitions: true

display_mode: light

beautify:
  enable: false
  field: post
  title_prefix_icon:
  title_prefix_icon_color:

font:
  global_font_size:
  code_font_size:
  font_family:
  code_font_family:

blog_title_font:
  font_link:
  font_family:

hr_icon:
  enable: true
  icon:
  icon_top:

# --------------------------------------
# Background effects
# --------------------------------------

canvas_ribbon:
  enable: false
  size: 150
  alpha: 0.6
  zIndex: -1
  click_to_change: false
  mobile: false

canvas_fluttering_ribbon:
  enable: false
  mobile: false

canvas_nest:
  enable: false
  color: '0,0,255'
  opacity: 0.7
  zIndex: -1
  count: 99
  mobile: false

activate_power_mode:
  enable: false
  colorful: true
  shake: true
  mobile: false

fireworks:
  enable: false
  zIndex: 9999
  mobile: false

click_heart:
  enable: false
  mobile: false

clickShowText:
  enable: false
  text:
  fontSize: 15px
  random: false
  mobile: false

# --------------------------------------
# Lightbox Settings
# --------------------------------------

lightbox: fancybox

# --------------------------------------
# Tag Plugins settings
# --------------------------------------

series:
  enable: false
  orderBy: 'title'
  order: 1
  number: true

abcjs:
  enable: false
  per_page: true

mermaid:
  enable: false
  code_write: false
  theme:
    light: default
    dark: dark
  open_in_new_tab: true
  zoom_pan: true

chartjs:
  enable: false
  fontColor:
    light: 'rgba(0, 0, 0, 0.8)'
    dark: 'rgba(255, 255, 255, 0.8)'
  borderColor:
    light: 'rgba(0, 0, 0, 0.1)'
    dark: 'rgba(255, 255, 255, 0.2)'
  scale_ticks_backdropColor:
    light: 'transparent'
    dark: 'transparent'

note:
  style: flat
  icons: true
  border_radius: 3
  light_bg_offset: 0

# --------------------------------------
# Other Settings
# --------------------------------------

pjax:
  enable: false
  exclude:

aplayerInject:
  enable: false
  per_page: true

snackbar:
  enable: false
  position: bottom-left
  bg_light: '#49b1f5'
  bg_dark: '#121212'

instantpage: false

lazyload:
  enable: false
  native: false
  field: site
  placeholder:
  blur: false

pwa:
  enable: false
  manifest:
  apple_touch_icon:
  favicon_32_32:
  favicon_16_16:
  mask_icon:

Open_Graph_meta:
  enable: true
  option:

structured_data:
  enable: false
  alternate_name:

css_prefix: true

inject:
  head:
    - <script charset="UTF-8" id="LA_COLLECT" src="https://sdk.51.la/js-sdk-pro.min.js"></script>
    - <script>LA.init({"id":"Jefs4FLXvLS3oCAK","ck":"Jefs4FLXvLS3oCAK"})</script>
    - <link rel="stylesheet" href="https://tmx.fishpi.cn/cdn/iconfont.css">
    - <link rel="stylesheet" href="https://tmx.fishpi.cn/cdn/style.css">
    - <script src="https://tmx.fishpi.cn/cdn/click.min.js"></script>
    - <script src="https://tmx.fishpi.cn/cdn/sakura-original.js"></script>
    - <script src="https://tmx.fishpi.cn/cdn/jquery.min.js"></script>
    - <script src="https://tmx.fishpi.cn/cdn/colorful-tag.js"></script>
  bottom:
    - <script>(function(){var div = document.createElement("div"); div.id = "web_bg";document.body.appendChild(div);})()</script>

# CDN Settings
CDN:
  internal_provider: local
  third_party_provider: local

  version: true

  custom_format:

  option:
    main_css: /css/index.css
    jquery: https://tmx.fishpi.cn/cdn/jquery.min.js
    main: /js/main.js
    utils: /js/utils.js

    pjax: https://tmx.fishpi.cn/cdn/pjax.min.js

    gitalk: https://tmx.fishpi.cn/cdn/gitalk.min.js
    gitalk_css: https://tmx.fishpi.cn/cdn/gitalk.min.css
    valine: https://tmx.fishpi.cn/cdn/Valine.min.js
    disqusjs: https://tmx.fishpi.cn/cdn/disqus.js
    disqusjs_css: https://tmx.fishpi.cn/cdn/disqusjs.css
    utterances: https://utteranc.es/client.js
    twikoo: https://tmx.fishpi.cn/cdn/twikoo.all.min.js
    waline_css: https://tmx.fishpi.cn/cdn/waline.css
    waline_js: https://tmx.fishpi.cn/cdn/waline.js

    addtoany: https://static.addtoany.com/menu/page.js
    sharejs: https://tmx.fishpi.cn/cdn/social-share.min.js
    sharejs_css: https://tmx.fishpi.cn/cdn/share.min.css

    local_search: /js/search/local-search.js
    algolia_js: /js/search/algolia.js
    algolia_search: https://tmx.fishpi.cn/cdn/instantsearch.min.js
    algolia_search_css: https://tmx.fishpi.cn/cdn/instantsearch.min.css

    mathjax: https://tmx.fishpi.cn/cdn/tex-mml-chtml.js
    katex: https://tmx.fishpi.cn/cdn/katex.min.css
    katex_copytex: https://tmx.fishpi.cn/cdn/copy-tex.min.js
    katex_copytex_css: https://tmx.fishpi.cn/cdn/copy-tex.css
    mermaid: https://tmx.fishpi.cn/cdn/mermaid.min.js

    busuanzi: //busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

    canvas_ribbon: https://tmx.fishpi.cn/cdn/canvas-ribbon.min.js
    canvas_fluttering_ribbon: https://tmx.fishpi.cn/cdn/canvas-fluttering-ribbon.min.js
    canvas_nest: https://tmx.fishpi.cn/cdn/canvas-nest.min.js

    lazyload: https://tmx.fishpi.cn/cdn/lazyload.iife.min.js
    instantpage: https://tmx.fishpi.cn/cdn/instantpage.min.js
    typed: https://tmx.fishpi.cn/cdn/typed.min.js

    fancybox_css: https://tmx.fishpi.cn/cdn/fancybox.css
    fancybox: https://tmx.fishpi.cn/cdn/fancybox.umd.js
    medium_zoom: https://tmx.fishpi.cn/cdn/medium-zoom.min.js

    snackbar_css: https://tmx.fishpi.cn/cdn/snackbar.min.css
    snackbar: https://tmx.fishpi.cn/cdn/snackbar.min.js

    activate_power_mode: https://tmx.fishpi.cn/cdn/activate-power-mode.min.js
    fireworks: https://tmx.fishpi.cn/cdn/fireworks.min.js
    click_heart: https://tmx.fishpi.cn/cdn/click-heart.min.js
    clickShowText: https://tmx.fishpi.cn/cdn/click-show-text.min.js

    fontawesome: https://tmx.fishpi.cn/cdn/fontawesomall.min.css

    translate: /js/tw_cn.js

    justifiedGallery_js: https://tmx.fishpi.cn/cdn/jquery.justifiedGallery.min.js
    justifiedGallery_css: https://tmx.fishpi.cn/cdn/justifiedGallery.min.css

    aplayer_css: https://tmx.fishpi.cn/cdn/APlayer.min.css
    aplayer_js: https://tmx.fishpi.cn/cdn/APlayer.min.js
    meting_js: https://tmx.fishpi.cn/cdn/Meting.min.js

    prismjs_js: https://tmx.fishpi.cn/cdn/prism.min.js
    prismjs_lineNumber_js: https://tmx.fishpi.cn/cdn/prism-line-numbers.min.js
    prismjs_autoloader: https://tmx.fishpi.cn/cdn/prism-autoloader.min.js
